### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by tonyliang19** [miniatureseal/dsci-310-group-10-GCC#103]
# Milestone 2 Feedback Group 10

> Issue: Originally we want to create a test folder, and move our test files in it, as well as renaming them.
We wanted to remove the leading numbers because it doesn't really abide by the standard naming format.
However we ran into the issue that the source method cannot find the file after renaming it.
Even though the files existed and the files' paths are typed out correctly, it still tried to find the files that were originally named like
(with leading numbers' version).
That's the reason we kept the naming format as this, even though this is not what we intended to do.
>
>
>**For this case, you can pretend that test cases are not named with leading numbers and placed in a test folder under the directory: "tests/testthat", and the test names start with "test-". Thus we cannot run this command "testthat::test_dir("tests/testthat")" either, as we can't rename and move the files.**
>

> I cannot pretend that ^, you had enough time to ask instructor's team to consult this, nearly all other groups managed to comply with this.
>

### Code is abstracted to functions with good function design 

- [x] Repeated code for setting recipe, spec and add to workflow **-5**
- [x] None of the function have proper exception handling for checking input (even `plot_fn` also has flaw) **-4**

### Functions are well documented

- [x] Repeated argument description for `fire_training_fn`, please be more specific on what differs the two parameters **-1**

#### Tests are written for each function, and work expected

- [x] None of tests run **-8**

#### Tests suite is of high quality

- [x] All tests except `plot_fn` have intermediate to low quality, wrong testing message (i.e. you checking if getting same output, but message is of same type of data), not robust enough to handle errors or edge cases, too few test cases **-6**

### Project file and directory struture organization

- [x] Tests not have right naming or not under right directory **-1**

### Analysis can be run reproducibly using doc in README

- [x] Please pay attention to your analysis's content, detail matters **-1**

![image](https://user-images.githubusercontent.com/83138402/226677573-4cf702f5-f7bb-4e75-868e-2cf4fee09df2.png)

- [x] Tests cases should not be run inside the actual analysis **-1**

Side note: you could add more detailed instruction from how to run the analysis, i.e. showing screenshot or just text explanation to click on the `Run All Cells`
