### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by tonyliang19** [miniatureseal/dsci-310-group-10-GCC#53]
Please read below feedbacks on things that you could've improve on for future milestones, **NOTE** if these are not fixed, marks will be deducted. If you have any questions on these feedbacks, please feel free to drop-in to my office hour or during lecture time

# Milestone 1 Feedback Group 10

### README.md
- Side Note: Having names instead of GitHub usernames could be better. It not only helps to grade (had to go on Canvas to see who were you), but also people knows who do contact in case you do not have your name on your GitHub Profile. *It is fine to keep it this way though*

- [x] Pin the version, names of packages required in your environment, we explicitly ask to rely on the README.md and not on `environment.yml` yet **-1**

- [x] Be more confident on your running instructions, specify which command is for which OS, and consider adding `cd` command as instruction. Plus, proper options of `-it` and `--rm` in your `docker run`, as others might not know that you could only have one port per allocation of server. **-1**
### Analysis

Although we focused more on the reproducibility of the analysis, you should still have some quality work in your analysis. I only saw some plots, but no methods/results at all other than showing correlation in your dataset. We expected it should lie on the richness of a dsci 100 final project.

- [x] Add more information about method carried over, and its corresponding results **-3**

- [x] Provide more detailed discussion, and try not to be too vague, give more insights from your result. **-3**
